"""fx rates and news

Revision ID: 50321f606619
Revises: c2a8e2f61270
Create Date: 2026-07-27 09:53:05.291295
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "50321f606619"
down_revision: str | None = "c2a8e2f61270"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("quoted_on", sa.Date(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quote_currency", "quoted_on"),
    )
    op.create_index(
        op.f("ix_fx_rates_quote_currency"), "fx_rates", ["quote_currency"], unique=False
    )
    op.create_index(
        op.f("ix_fx_rates_quoted_on"), "fx_rates", ["quoted_on"], unique=False
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("publisher", sa.String(length=128), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("topic", sa.String(length=32), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_items_guid"), "news_items", ["guid"], unique=True)
    op.create_index(
        op.f("ix_news_items_published_at"), "news_items", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_news_items_topic"), "news_items", ["topic"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_items_topic"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_published_at"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_guid"), table_name="news_items")
    op.drop_table("news_items")
    op.drop_index(op.f("ix_fx_rates_quoted_on"), table_name="fx_rates")
    op.drop_index(op.f("ix_fx_rates_quote_currency"), table_name="fx_rates")
    op.drop_table("fx_rates")
    # ### end Alembic commands ###
