"""user activation

Revision ID: 7e13ffe077f7
Revises: 50321f606619
Create Date: 2026-07-27 14:48:11.222308
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7e13ffe077f7"
down_revision: str | None = "50321f606619"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-edited from the autogenerated version. Autogenerate emitted a bare
    # NOT NULL column, which fails on any table that already has rows —
    # "column is_active contains null values". A model-level `default=True` is
    # applied by Python on insert, so it does nothing for a backfill.
    #
    # The three-step form is the safe one: add nullable, backfill, then enforce.
    # server_default is dropped afterwards so the constraint lives in the model
    # rather than being silently duplicated in the schema.
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    op.alter_column("users", "is_active", nullable=False, server_default=sa.true())
    op.alter_column("users", "is_active", server_default=None)
    op.add_column("users", sa.Column("created_by", sa.Integer(), nullable=True))
    # The index and FK below are autogenerate's own lines, left as emitted.
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_foreign_key("fk_users_created_by", "users", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_created_by", "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_column("users", "created_by")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
