"""market prices

Revision ID: c2a8e2f61270
Revises: 987c943c8d93
Create Date: 2026-07-27 09:40:04.009384
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c2a8e2f61270"
down_revision: str | None = "987c943c8d93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("commodity_id", sa.Integer(), nullable=True),
        sa.Column("quoted_on", sa.Date(), nullable=False),
        sa.Column("close_usd_per_bu", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["commodities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "quoted_on"),
    )
    op.create_index(
        op.f("ix_market_prices_quoted_on"), "market_prices", ["quoted_on"], unique=False
    )
    op.create_index(
        op.f("ix_market_prices_symbol"), "market_prices", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_prices_symbol"), table_name="market_prices")
    op.drop_index(op.f("ix_market_prices_quoted_on"), table_name="market_prices")
    op.drop_table("market_prices")
    # ### end Alembic commands ###
